### PR TITLE
User's Location fetched using GPS

### LINKED ISSUE #93: Location fetching missing and Textcontroller overridden
**Describe the bug**
In complete profile page, "name" and "location" fields are using the same text controller. Also user's live Location fetching functionality is missing in the app.

**To Reproduce**
1. Go to complete profile page
2. Click on name field
3. Write the name
4. you can see the entered value in name field is also entered into location field bydefault. 

**Expected behavior**
In complete profile page,when you'll enter the value in name field,
location field also captures that value by default.

**Screenshots**
image

**Smartphone (please complete the following information):**
Device: Realme7
OS: Android 11

### PR DESCRIPTION
**Pull request by theshubh007**
## Related Issue

Closes #93 

## Description
->In complete profile page,I had added the seperate controller for location field.
->Fetched user's live location using GPS in the complete profile page. 
->After fetching Location as Geopoint used that value to find the pincode of area.
->Then in dbcontroller I have added this value in create profile schema to store the data in Firebase.

## Screenshots
WhatsApp Image 2023-08-08 at 21 55 22
WhatsApp Image 2023-08-08 at 21 55 19

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

File: lib/controller/database_controller.dart [hunk 1]
```diff
@@ -30,7 +31,7 @@ class DatabaseController extends GetxController {
       },
       "upi": "9876543210@upi",
       "type": "veg",
-      "loc": const GeoPoint(30.2829736, 76.7105632),
+      "loc":restaurantlocation==""? const GeoPoint(30.2829736, 76.7105632):restaurantlocation,
```
Comment (m0hit-kumar2) [inline lib/controller/database_controller.dart:34]: why are you fixing the location, make it dynamic

File: lib/views/admin/complete_profile/complete_profile.dart [hunk 2]
```diff
@@ -18,19 +20,77 @@ class _AdminCompleteProfileState extends State<AdminCompleteProfile> {
...
       .doc("SqNrahYI1KhQaVZXzkcN")
       .get();
 
+  @override
+  void initState(){
+    // TODO: implement initState
+    super.initState();
+     getCurrentPosition();
+  }
+
```
Comment (m0hit-kumar2) [inline lib/views/admin/complete_profile/complete_profile.dart:93]: dispose it also

File: lib/controller/database_controller.dart (hunk 1 above)
Comment (theshubh007) [reply lib/controller/database_controller.dart:34]: It is a default value, reason behind is whenever any error occurs while fetching the value from gps location then in default case it will consider it.

Comment (theshubh007) [reply lib/controller/database_controller.dart:34]: It is a default value, reason behind is whenever any error occurs while fetching the value from gps location then in default case it will consider it.

File: lib/views/admin/complete_profile/complete_profile.dart (hunk 2 above)
Comment (theshubh007) [reply lib/views/admin/complete_profile/complete_profile.dart:93]: Ok

**Review by m0hit-kumar — APPROVED** [review]
